accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"), #not yet created
]

blog_project/urls.py
#blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("blogapp.urls")),
]

blogapp/urls.py
from django.urls import path
from .views import (
BlogListView,
BlogDetailView,
BlogCreateView,
BlogUpdateView,
BlogDeleteView
)
urlpatterns = [
path("post/new/", BlogCreateView.as_view(), name="post_new"),
path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
path("post/<int:pk>/delete/", BlogDeleteView.as_view(),name="post_delete"),
path("", BlogListView.as_view(), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

blogapp/models.py
from django.db import models
from django.urls import reverse #to reference an object by its URL template name.

class Post(models.Model): #provides access to everything within django.db.models.Models
    title = models.CharField(max_length=200) #CharField, limited to 200 characters
    
    author = models.ForeignKey( #ForeignKey field, allows for a many-to-one relationship
        'auth.User', #One user can be the author of many blog posts but not reversible
        on_delete=models.CASCADE, #For all many-to-one relationships we must specify an on_delete option
    )

    body = models.TextField() #TextField, automatically expand as needed to fit the user’s text
    
    
    def __str__(self): #To provide a human-readable version of the model in the admin or Django shell
        return self.title

    def get_absolute_url(self): #Tells Django how to calculate the canonical URL for our model object
        return reverse('post_detail', kwargs={'pk': self.pk})

    

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blogapp/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Post
from django.urls import reverse_lazy
class BlogListView(ListView):
    model = Post
    template_name = "home.html"

    
class BlogDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"


class BlogCreateView(CreateView):
    model = Post
    template_name = "post_new.html"
    fields = ["title", "author", "body"]

class BlogUpdateView(UpdateView):
    model = Post
    template_name = "post_edit.html"
    fields = ["title", "body"]
    

class BlogDeleteView(DeleteView):
    model = Post 
    template_name = "post_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
<!-- templates/base.html -->
{% load static %} <!-- new -->
<html>
    <head>
        <title>My blog</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <a href="{% url 'login' %}">Log In</a> |
        <a href="{% url 'signup' %}">Sign Up</a>
    </head>
    <body>
        <header>
            <div class="nav-left">
                <h1><a href= "{% url 'home' %}">Django blog</a></h1>
            </div>
            <!--make sure the user is logged in to create a new post-->
            {% if user.is_authenticated %}
                <div class="nav-right">
                    <a href= "{% url 'post_new' %}">+ New Blog Post</a>    
                </div>
            {% else %}
                <div class = "nav-right">
                    <a href="{% url 'login' %}">Log In To Post</a>
                </div>
            {% endif %}        
        </header>
        <!--to show if the user is logged in -->
        {% if user.is_authenticated %}
        <p>Welcome {{ user.username }}!</p>

        {% else %}
        <p>You are not logged in.</p>

        {% endif %}
       
    <div>
        {% block content %}
        {% endblock content %} 
        {% if user.is_authenticated %}
            <p><a href="{% url 'logout' %}">Log out</a></p>
        {% else %}
            <a href="{% url 'login' %}">Log In</a>
        {% endif %}
    </div>
    </body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}


{% block content %}
{% for post in post_list %}
<div class="post-entry">
    <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>        
<p>{{ post.body }}</p>
</div>
{% endfor %}
{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}
{% block content %}
<!--MAKE SURE THE USER IS LOGGED IN TO DELETE POST-->
{% if user.is_authenticated %}
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm">
    </form>
{% else %}
    <p>Please login to delete Post</p>
{% endif %}
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}
{% block content %}
<div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.body }}</p>
</div>
<a href="{% url 'post_edit' post.pk %}">+ Edit Blog Post</a>
<p><a href="{% url 'post_delete' post.pk %}">+ Delete Blog Post</a></p>

{% endblock content %}

templates/post_edit.html
{% extends "base.html" %}
{% block content %}

<!--MAKE SURE THE USER IS LOGGED IN TO EDIT A POST-->
{% if user.is_authenticated %}
    <h1>Edit post</h1>
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    </form>
{% else %}
    <p>Please Log In To Edit</p>
{% endif %}

{% endblock content %}

templates/post_new.html
{% extends "base.html" %}
{% block content %}
<h1>New post</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>
{% endblock content %}